services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dep
    image: portfolio
    container_name: portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "pnpm install && pnpm run dev"
