services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    image: portfolio
    container_name: portfolio
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - node_modules-portfolio:/app/node_modules
    environment:
      - CI=true
volumes:
  node_modules-portfolio: